### ISSUE TITLE
Не качает книги

### ISSUE THREAD

**Issue by vadimkara** [bookpauk/inpx-web#1]
ERROR: getBookLink error: ENOENT: no such file or directory, open '/share/CACHEDEV2_DATA/Soft/Books/fb2.Flibusta.Net/undefined'

Пишет ошибку 404 в логе вот такое.

**Comment by bookpauk** [comment]
Интересно. Приведите, пожалуйста, больше данных.
Какой inpx используете, с какими параметрами запускаете, какой файл пытаетесь скачать (параметры поиска)?

**Comment by vadimkara** [comment]
https://booktracker.org/viewtopic.php?t=46979
Торрент полная флибуста отсюда ложу в папку вместе с файлами запускаю. Сканирование проходит книги вижу но как только нажимаю скачать или прочитать выдает ошибку 404 а в логе такое. Пробовал как под линукс так и под виндой. Результат тот же самый.

**Comment by bookpauk** [comment]
Баг воспроизвел, благодарю за помощь, буду исправлять.

**Comment by ImmortAlexGM** [comment]
Не похоже что исправлено, так и повторяется.
Окружение: Ubuntu 22.10 x64
Кладу inpx-web 1.1.3 прям в каталог с флибустой, стоя там же запускаю, после создания базы всё как бы работает без ошибок, но скачать файл по-прежнему не удаётся с точно такой же ошибкой, как у топикстартера, с /indefined в конце пути.

**Comment by bookpauk** [comment]
В 1.1.3 надо пересоздать БД с ключом --recreate.
Обновитесь до 1.1.4, там добавлено автообновление БД, проблема должна исчезнуть.
