### ISSUE TITLE
При использовании фильтров моргает список найденных авторов и пропадает.

### ISSUE THREAD

**Issue by vadimkara** [bookpauk/inpx-web#10]
![image](https://user-images.githubusercontent.com/7599876/208489002-27ddcb9f-533a-4692-82c9-72ee392acedf.png)

**Comment by Weegley** [comment]
Не подтверждается
![Uploading Screenshot_20221219_211811_Firefox.jpg…]()

**Comment by vadimkara** [comment]
У меня первый раз тоже открылось после отрытия пары книг все пропало.

**Comment by vadimkara** [comment]
![image](https://user-images.githubusercontent.com/7599876/208494823-a06a8348-77e4-42da-994a-e341da3ac3b0.png)

**Comment by Weegley** [comment]
Вкладка "сеть"
Скорее всего там сбой. Может, соединиться не может.
[работает](https://youtu.be/stDG8fpXb_M)

**Comment by vadimkara** [comment]
Сборка под линух от автора. С сетью проблем быть не может все в локалке стоит. Тут что то точно с количеством книг связано. Так как на эту переменную. Ругаеться.

**Comment by xboxones1** [comment]
Под Линуксом, работает без проблем. 
![1](https://user-images.githubusercontent.com/91512529/208679290-8099f398-c345-4478-a2a9-f03e8298d1f5.jpg)

**Comment by xboxones1** [comment]
Да, при большом значении отображении книг, у меня такое же поведение.

**Comment by bookpauk** [comment]
Воспроизвести нигде не могу, ни на десктопе, ни на смартфоне. Причина проблемы остается невыясненной.
Особое спасибо за скриншоты, поставлю заплатку в проблемном месте.

**Comment by bookpauk** [comment]
Просьба проверить в 1.4.1

**Comment by vadimkara** [comment]
Ошибка исчезла в 1.4.1
