### ISSUE TITLE
Не работает за реверс-прокси 

### ISSUE THREAD

**Issue by Insaned79** [bookpauk/inpx-web#14]
При попытке настроить обратный ssl прокси (пробовал и apache и nginx) - не работает. На экран выдается ообщение об ошибке, в логах приложения ошибок нет, в логах веб-сервера ошибок нет.
![изображение](https://user-images.githubusercontent.com/11388816/217492349-202b409e-f835-449a-aaa5-ba909f3eb483.png)

**Comment by Weegley** [comment]
На апаче всё работает.
Нужно пробрасывать как http  так и websocket
Завтра скину свой конфиг для примера

**Comment by bookpauk** [comment]
Еще актуально?

**Comment by Insaned79** [comment]
Спасибо. Разобрался. Если кому-то понадобиться, вот мой пример конфига для nginx:

```
server {
    listen 12379 ssl;
    server_name subdomain.domain.com;

    ssl_certificate /etc/letsencrypt/live/subdomain.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/subdomain.domain.com/privkey.pem;
    ssl_dhparam /etc/letsencrypt/live/subdomain.domain.com/dhparams.pem;

    location / {
        proxy_pass http://localhost:12380/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}
```
