### ISSUE TITLE
Механизм обновления?

### ISSUE THREAD

**Issue by ra3ggi** [bookpauk/inpx-web#15]
Прежде всего хочу выразить огромную благодарность , за Ваш проект! 
Я перебрал несколько вариантов для своей локальной библиотеки. Остановился на inpx-web за мощный и удобный поиск, скорость работы и отсутствие нагрузки на систему.
Есть ли какой-то механизм обновления ? Ведь , сами понимаете, следить за авторской страничкой на гитхабе - это не вариант для постоянного использования.
PS Честно говоря, у вашего проекта мало конкурентов по легкости использования и качеству работы. Но немного хромает дизайн. Если бы немного поработать на ним  - думаю, проект бы взлетел совсем иначе. 
Удачи!

**Comment by bookpauk** [comment]
Насчет обновления - подумаю, проблема в том, что это веб приложение. Много вы видели веб сайтов, кторые позволяют пользователям обновлять себя, при наличии новой версии?

Дизайн - да, какой уж есть. Я же ни разу не дизайнер. Цель была - максимально простой и удобный поиск, а внешний вид уже как получился :) Ну и за массовостью не гонюсь...

**Comment by ra3ggi** [comment]
Да , что-то я не подумал - обновление по "нажатию на кнопку" наверное не реально. Ну хоть информацию видеть , что "Доступна новая версия".
Удачи!
