### ISSUE TITLE
Не качает книги

### ISSUE THREAD

**Issue by vadimkara** [bookpauk/inpx-web#2]
Скачал новую версию пересоздал базу. Ошибка не исчезла(

**Comment by vadimkara** [comment]
Почистил кеш все прошло

**Comment by bookpauk** [comment]
Да, верно, забыл упомянуть, что надо запускать с --recreate или удалить папку db. В общем, пересоздать базу.
Выпущу, пожалуй, 1.1.4 с автообновлением БД.
