### ISSUE TITLE
Проблема авторизации мобильных OPDS клиентов

### ISSUE THREAD

**Issue by AdeptMechanicum** [bookpauk/inpx-web#21]
Не авторизуется CoolReader при попытке доступа к opds-серверу. В конфиге прописываю логин-пароль, ту же пару закидываю в конфиг каталога на читалке - и происходит ошибка 401. При этом с компа перехожу по ссылке на opds-каталог - у меня исправно спрашивается логин и пассворд, если ввожу то что надо - выводит корректно (вроде корректно, понятия не имею как должен выглядеть ответ OPDS-сервера) всё. Fbreader тоже не авторизуется. При этом если убираю авторизацию - на обоих подопытных читалках всё работает как надо

**Comment by Nab0y** [comment]
Присоединяюсь к оратору, та же проблема, пришлось убрать логин/пароль с opds.

**Comment by FlySt0nE** [comment]
На AlReaderX Pro на читалке ONIX так же, при настроенной авторизации в конфиге opds inpx-web и настройках в приложении авторизация не воспринимается, пишет, что библиотека доступна только зарегистрированным пользователям. При доступе через Web все работает корректно.

**Comment by bookpauk** [comment]
Что удалось выяснить:
- присутствует баг в CoolReader, присылает неверный заголовок Authorization, без указания схемы Basic, присылает почему-то только credentials. В CoolReader GL такого бага нет, рекомендую переходить на него
- в AlReaderX также есть баг, вообще не присылает заголовка Authorization, даже при правильном указании логина/пароля

В общем, это проблемы указанных читалок. Если у вас есть примеры, когда эти читалки нормально авторизуются на других opds-серверах, тогда приведите пример. А пока обращение закрываю.
