### ISSUE TITLE
Не сохраняет настройку

### ISSUE THREAD

**Issue by vadimkara** [bookpauk/inpx-web#3]
Не сохраняет настройку Результатов на странице постоянно сбрасывает на 20

**Comment by bookpauk** [comment]
Возможно, вы открываете сохраненную закладку или URL с присутствующим параметром limit? Чтобы правильно отобразить результат поиска при введении URL, в нем присутствуют параметры page и limit. Поэтому limit сбрасывается к значению из URL.

Если открывать без параметров (напр. https://lib.omnireader.ru/), то limit берется из сохраненного значения настройки.

**Comment by bookpauk** [comment]
Возможно, имеет смысл в URL подставлять значение recnum=(page - 1)*limit
Тогда можно будет вычислять page на основании сохраненного limit, чтобы показать примерно те же найденные результаты.
Либо вообще убрать limit из URL и сбрасывать поиск на первую страницу при загрузке сайта.

**Comment by vadimkara** [comment]
Ага все верно не заметил как сохранил дил с параметром лимит.
