### ISSUE TITLE
Android-читалки не очень хорошо работают с OPDS

### ISSUE THREAD

**Issue by ImmortAlexGM** [bookpauk/inpx-web#4]
Возможно, что-нибудь можно подкрутить для большей совместимости, но на данный момент ситуация такая:
FBReader - не работает ни поиск, ни просто показ всего списка, ошибок не выдаёт - просто ничего не показывает, словно каталог пустой
Moon Reader - качает gzip-сжатые FB2, но не понимает, что они сжатые, пытается показать как есть, но не может
CoolReader - работает хорошо

На компе проверял только в Foilante - тоже работает.

**Comment by bookpauk** [comment]
Все баги подтверждаю, будем исправлять.

**Comment by Weegley** [comment]
Alreader работает прекрасно. Включая поиск.
Кстати, сам каталог организован довольно удачно.

**Comment by Alex-AVS** [comment]
Во-первых - респект за труд. Весьма не дурственно получилось.
Во-вторых - насчёт "CoolReader - работает хорошо" есть возражения
1. В "старой" версии не работает при наличии пароля на opds - 401. Возможно, проблема самого ридера. Имя пользователя без разницы есть-нет, отрабатывает норм. CR GL работает с паролем нормально.
2.  При скачивании файла он сохраняется как .fb2.zip, хотя внутри просто текст. В результате скачанное CR не может открыть и файл на диске не показывает. Полагаю, это из-за type, указанного в ссылке: 
<link href="/book/b1043e23ebde2dea2b174f979c1f052b55c239e475f55d64712ef2b33f0a580a" rel="http://opds-spec.org/acquisition" type="application/**fb2+zip**"/>
Т.к. в заголовках при скачивании имя файла без zip. 
Тоже косяк CR конечно, но, наверное, можно  поправить бы.

**Comment by bookpauk** [comment]
> Alreader работает прекрасно. Включая поиск. Читалка Pocketbook 632 не работает...
Просьба уточнить, как именно не работает, если не показывает список, то этот баг будет исправлен.

**Comment by bookpauk** [comment]
> 1. В "старой" версии не работает при наличии пароля на opds - 401. Возможно, проблема самого ридера...

Скорее всего, проблема ридера, т.к. используется стандартный моудль для node-express. При тестировании тоже обратил внимание на этот момент. В других читалках BasicAuth работает нормально.

> 2. При скачивании файла он сохраняется как .fb2.zip, хотя внутри просто текст. В результате скачанное CR не может открыть и файл на диске не показывает. Полагаю, это из-за type, указанного в ссылке:
>    `<link href="/book/b1043e23ebde2dea2b174f979c1f052b55c239e475f55d64712ef2b33f0a580a" rel="http://opds-spec.org/acquisition" type="application/**fb2+zip**"/>`

Есть какие-то странности с type, разные читалки по-разному ведут себя с этим параметром, посмотрю, что можно сделать.
