### ISSUE TITLE
Сборка для Linux arm64

### ISSUE THREAD

**Issue by xboxones1** [bookpauk/inpx-web#5]
Добрый день. 
Возможна ли сборка релизов для Linux arm64? Желательно без стрипов либ, чтобы был возможен запуск на легковесных linux по типу CoreElec.

**Comment by bookpauk** [comment]
Хмм, вроде собралось, и под QEMU даже запускается.

**Comment by bookpauk** [comment]
Сборки для Linux arm64 будут доступны со следующего релиза. В ветке develop можно уже сейчас собрать релиз самостоятельно.

**Comment by xboxones1** [comment]
Собрал, работает отлично. Спасибо.
