### ISSUE TITLE
Настройки веба вынести в конфиг, либо как опции командной строки

### ISSUE THREAD

**Issue by xboxones1** [bookpauk/inpx-web#6]
При очистке кеша в браузере настройки веба сбрасываются, что не очень удобно. Если возможно, предлагаю их так же вынести в конфиг, либо добавить как опции командной строки.

**Comment by Weegley** [comment]
Поддерживаю!
И не только веба!
  --lib-dir=<dirpath>
  --inpx=<filepath>
Тоже

**Comment by bookpauk** [comment]
> При очистке кеша в браузере настройки веба сбрасываются, что не очень удобно. Если возможно, предлагаю их так же вынести в конфиг, либо добавить как опции командной строки.

Чтобы не было недопонимания, имеются ввиду настройки веб-приложения, такие как "Результатов на странице", "Показывать ..,", "Кешировать запросы"? Или что-то другое?

Опции командной строки пожалуй да, можно сдублировать в конфиг.
