### ISSUE TITLE
OPDS сломан для Foliate

### ISSUE THREAD

**Issue by ImmortAlexGM** [bookpauk/inpx-web#7]
Возможно, не ваша ошибка.
Я в прошлый раз ошибался, когда сказал, что в Foliate работает OPDS. По-видимому, для сколько-нибудь длинных названий книг оно не работало и в 1.3.3.
Ошибка в логе такая:

JS ERROR: WebKit2.DownloadError: Error opening file “/home/alexey/.local/share/com.github.johnfactotum.Foliate/books/ypqN0dyCQtOB2Gy7v8EfZjsXrWod32qv%2B0pzWzMGNFA%3D@2022-12-07T17%3A05%3A29Z@%D0%A1%D1%82%D0%B8%D0%B2%D0%B5%D0%BD%D1%81%D0%BE%D0%BD%20%D0%9D%D0%B8%D0%BB%20-%20%D0%97%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%20%D0%A1%D0%BE%D0%BB%D0%BE%D0%BC%D0%BE%D0%BD%D0%B0.fb2.zip.wkdownload”: File name too long

Кто формирует такое длинное имя - вы или автор Foliate - я не знаю, но оно, по-видимому, превышает возможности файловой системы. Вдруг что-то можно исправить?

**Comment by xboxones1** [comment]
Для  избежания подобных проблем, можно добавить опцию для преобоазования названия в транслит.

**Comment by xboxones1** [comment]
Для избежания подобных проблем, думаю нужно отдавать название  книг в транслите
