### ISSUE TITLE
Жанры в OPDS

### ISSUE THREAD

**Issue by xboxones1** [bookpauk/inpx-web#9]
Добрый день. 
Не хватает раздела "Жанры" на главной в opds, для примера можно взять flibusta.
К примеру, я не знаю конкретного названия книги, но хочу что-нибудь почитать из фантастики, захожу в жанр Фантастика, выбираю поджанр и получаю список книг с синопсисом, выбираю понравившееся и читаю.  В целом сейчас не очень удобно, что приходится прокликивать весь алфавит, это удобно когда хочешь почитать, что-то конкретное, но не очень когда просто выбираешь.

**Comment by Weegley** [comment]
Поддержу

**Comment by bookpauk** [comment]
Проблема в том, что вытащить аннотацию не так просто, книги то в архивах. Теоретически возможно, конечно, но придется менять подход:
- вариант 1: вытаскиваем все аннотации в момент формирования БД (можно в фоновом режиме) и сохраняем их в таблицу для быстрого доступа
- вариант 2: вытаскиваем аннотации в момент запроса, но тогда сильно увеличится время выполнения запроса

В общем, пока предлагаю добавить в opds раздел "Жанры" (а также и в поиск), где после выбора жанра будет отображаться список найденных книг как при поиске - с постраничным листанием по 100 штук.
Больше пока ничего сделать нельзя.

**Comment by bookpauk** [comment]
Вообще, для такого поиска можно воспользоваться веб-интерфейсом, где намного больше возможностей сократить поиск - выбор по оценкам, нескольким жанрам-поджанрам, времени поступления в библиотеку и т.д.
А далее, уже выбранные книги по автору-названию можно загружить через opds.
Хоть это и неудобно конечно. Но именно для этого и задумывался веб-интерфейс, opds все же ограниченный стандарт.

**Comment by xboxones1** [comment]
Спасибо, все работает и аннотация в том числе.

**Comment by bookpauk** [comment]
Обнаружил недочет, в 1.5.0 неправильно работает поиск в жанрах при нажатии "[Следующая страница]".

Исправил в 1.5.1
